name: compile

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          curl https://zonefiles.io/f/compromised/ip/live/ | tail -n+2 | while read in; do echo "|$in|"; done > compromised_ips.txt
          curl https://zonefiles.io/f/compromised/ip/full/ | tail -n+2 | while read in; do echo "|$in|"; done > compromised_ips_full.txt
          git config --global user.name "prokrypt"
          git config --global user.email "username@users.noreply.github.com"
          git add compromised_ips.txt compromised_ips_full.txt
          git commit -m "update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
